# Generated by Django 3.2.17 on 2023-02-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('stu_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('school', models.CharField(max_length=100)),
                ('present_class', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
