# Generated by Django 3.2.17 on 2023-02-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_student_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='buddy',
            fields=[
                ('buddy_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('buddy_name', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('designation', models.CharField(max_length=100)),
                ('workplace', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='school_admin',
            fields=[
                ('school_admin_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('school_admin_name', models.CharField(max_length=100)),
                ('school_id', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('designation', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
