# Generated by Django 3.2.17 on 2023-02-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_buddy_school_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='school_admin',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
